name: Timmo
favicon: null
layout_spectrum: 0.8082510316744447
typography_spectrum: 0.6514326040633023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4732144025620073
  lightness: 0.07558293966576457
  saturation: 0.7795802722685039
  rhythmicContrast: 0.6955297635868192
purpose: []
